"""
Pre-defined GCP service groups for targeted enumeration.
Values are GCP permission prefixes matched against GCP_PERMISSIONS entries.
"""

GCP_SERVICE_GROUPS: dict[str, list[str]] = {
    "compute": [
        "compute",
        "tpu",
        "batch",
        "appengine",
        "run",
    ],
    "network": [
        "networksecurity",
        "networkconnectivity",
        "networkservices",
        "networkmanagement",
        "servicenetworking",
        "dns",
        "vpcaccess",
        "ids",
        "domains",
    ],
    "storage": [
        "storage",
        "file",
        "storagetransfer",
    ],
    "databases": [
        "bigtable",
        "spanner",
        "datastore",
        "alloydb",
        "memcache",
        "redis",
        "firebasedatabase",
        "bigquery",
        "analyticshub",
    ],
    "serverless": [
        "cloudfunctions",
        "run",
        "cloudtasks",
        "cloudscheduler",
        "eventarc",
        "workflows",
        "pubsub",
        "pubsublite",
        "apigateway",
    ],
    "iam": [
        "iam",
        "resourcemanager",
        "accessapproval",
        "orgpolicy",
        "iap",
        "policyanalyzer",
        "policysimulator",
        "serviceusage",
        "servicemanagement",
        "managedidentities",
    ],
    "security": [
        "cloudkms",
        "secretmanager",
        "binaryauthorization",
        "containeranalysis",
        "securitycenter",
        "cloudsecurityscanner",
        "privateca",
        "certificatemanager",
        "dlp",
        "beyondcorp",
        "ondemandscanning",
    ],
    "monitoring": [
        "monitoring",
        "logging",
        "cloudtrace",
        "errorreporting",
        "cloudasset",
        "cloudprofiler",
    ],
    "ai": [
        "aiplatform",
        "ml",
        "speech",
        "dialogflow",
        "contactcenterinsights",
        "contactcenteraiplatform",
        "discoveryengine",
        "retail",
        "recommender",
        "dataform",
    ],
    "devops": [
        "cloudbuild",
        "clouddeploy",
        "artifactregistry",
        "source",
        "gkehub",
        "gkebackup",
        "gkeonprem",
        "container",
    ],
    "data": [
        "dataproc",
        "dataflow",
        "dataplex",
        "datacatalog",
        "datastream",
        "datamigration",
        "datafusion",
        "datapipelines",
        "datalabeling",
        "datalineage",
        "composer",
        "metastore",
    ],
}
